# File generated by WEACEInstall on 2010-01-29 18:08:19.
# !!! DO NOT MODIFY IT as it is used to keep track of what has been installed using WEACE Toolkit.
{
  :InstallationDate => '2010-01-29 18:08:19',
  :InstallationParameters => '',
  :Description => 'Redmine adapted to WEACE Slave as a Ticket Tracker.',
  :Author => 'muriel@x-aeon.com'
}
