# This file has been generated by WEACE Toolkit Installer on 2009-12-09 14:43:35
# It contains information needed by every WEACE component installation to retrieve the environment on which it is being installed.

{
  :ProviderType => 'Master',
  :ProviderID => 'DummyMasterProvider',
  :Parameters => [
    
  ]
}
