# File generated by WEACEInstall on 2010-01-29 16:29:24.
# !!! DO NOT MODIFY IT as it is used to keep track of what has been installed using WEACE Toolkit.
{
  :InstallationDate => '2010-01-29 16:29:24',
  :InstallationParameters => '--shelldir %{ProductDir}/WEACETools',
  :Description => 'The WEACE Master Server.',
  :ProviderID => 'DummyMasterProviderWithShell',
  :Author => 'murielsalvan@users.sourceforge.net'
}
