# File generated by WEACEInstall on 2010-01-29 16:29:24.
# !!! DO NOT MODIFY IT as it is used to keep track of what has been installed using WEACE Toolkit.
{
  :Type => 'Slave',
  :InstallationDate => '2010-01-29 16:29:24',
  :InstallationParameters => '',
  :Description => 'This Slave Product is used for regression purposes only.',
  :Product => 'DummyProduct',
  :Author => 'murielsalvan@users.sourceforge.net'
}
