# Usage: This file is used by other files.
# Do not call it directly.
#
# Check http://weacemethod.sourceforge.net for details.
#--
# Copyright (c) 2009 Muriel Salvan (murielsalvan@users.sourceforge.net)
# Licensed under BSD LICENSE. No warranty is provided.
#++

module WEACEInstall

  module Master
  
    class WEACEMasterServer
    
      include WEACEInstall::Common
      include WEACE::Toolbox
      
      # Install for real.
      # This is called only when check method returned no error.
      #
      # Return:
      # * _Exception_: An error, or nil in case of success
      def execute
        rError = nil
        
        rError, lProviderEnv = getProviderEnv('Master', @ProviderID, @AdditionalParameters)
        if (rError == nil)
          # Store the way we retrieved the provider config in a file to be parsed for Adapters installations
          saveProviderConfig('Master', @ProviderID, @AdditionalParameters)
          if (lProviderEnv[:CGI] != nil)
            # Generate the cgi script that will give details about the installed WEACE Master Adapters
            lShowComponentsFileName = "#{lProviderEnv[:CGI][:InternalDirectory]}/WEACE/ShowWEACEMasterInfo.cgi"
            logDebug "Generate CGI script that shows installed WEACE Master Adapters (#{lShowComponentsFileName}) ..."
            require 'fileutils'
            FileUtils.mkdir_p(File.dirname(lShowComponentsFileName))
            File.open(lShowComponentsFileName, 'w') do |oFile|
              oFile << "\#!/usr/bin/env ruby
\# This file has been generated by the installation of WEACE Master Server
\# Print header
puts 'Content-type: text/html'
puts ''
puts ''
begin
  \# Add WEACE Toolkit path to Ruby's path
  $LOAD_PATH << '#{File.expand_path(@WEACELibDir)}'
  require 'WEACEToolkit/Master/Server/ShowWEACEMasterInfo'
  WEACE::Master::Dump_HTML.new.dumpWEACEMasterInfo_HTML
rescue Exception
  puts \"WEACE Master Installation is corrupted: \#{$!}\"
end
"
            end
            FileUtils.chmod(0755, lShowComponentsFileName)
          end
          logInfo 'WEACE Master Server installed successfully. You can install WEACE Master Adapters.'
        end

        return rError
      end

    end
  
  end
  
end
