# Usage: This file is used by other files.
# Do not call it directly.
#
# Check http://weacemethod.sourceforge.net for details.
#--
# Copyright (c) 2009 Muriel Salvan (murielsalvan@users.sourceforge.net)
# Licensed under BSD LICENSE. No warranty is provided.
#++

module WEACEInstall

  module Master
  
    class WEACEMasterServer
    
      include WEACEInstall::Common
      
      # Execute the installation
      #
      # Parameters:
      # * *iParameters* (<em>list<String></em>): Additional parameters to give the installer
      # Return:
      # * _Exception_: An error, or nil in case of success
      def execute(iParameters)
        rError = nil
        
        rError, lProviderConfig = getProviderConfig('Master', @ProviderID, iParameters)
        if (rError == nil)
          # Store the way we retrieved the provider config in a file to be parsed for Adapters installations
          saveProviderConfig('Master', @ProviderID, iParameters)
          if (lProviderConfig[:CGI] != nil)
            # Generate the cgi script that will give details about the installed WEACE Master Adapters
            lShowAdaptersFileName = "#{lProviderConfig[:CGI][:InternalDirectory]}/WEACE/ShowWEACEMasterInfo.cgi"
            logDebug "Generate CGI script that shows installed WEACE Master Adapters (#{lShowAdaptersFileName}) ..."
            File.open(lShowAdaptersFileName, 'w') do |iFile|
              iFile << "#!/usr/bin/env ruby
# This file has been generated by the installation of WEACE Master Server
require 'WEACEToolkit/Master/Server/ShowWEACEMasterInfo'
# Print header
puts 'Content-type: text/html'
puts ''
puts ''
WEACE::Master::Dump_HTML.new.dumpWEACEMasterInfo_HTML
"
            end
            FileUtils.chmod(0755, lShowAdaptersFileName)
            # Generate the environment file
            lEnvProviderFileName = "#{@WEACERepositoryDir}/Env_Master.rb"
            logDebug "Generate environment file that will be used by WEACE Master Adapters' installers (#{lEnvProviderFileName}) ..."
            File.open(lEnvProviderFileName, 'w') do |iFile|
              iFile << "# This file has been generated by Install_WEACEMasterServer.rb.
# It is used to give the environment of this provider to the WEACE Master Adapters installers.
# This avoids developers to always give those parameters to any of the adapters installers.
# Its content depends on the WEACE Master Server type (SourceForge, RubyForge...)
module WEACEInstall

  module Master

    class ProviderEnv
    
      attr_reader :ProviderType
      attr_reader :CGIURL
    
      # Constructor
      def initialize
        @ProviderType = '#{@ProviderID}'
        @CGIURL = '#{lProviderConfig[:CGI][:URL]}'
      end
      
    end
    
  end
  
end
"
            end
          end
          logInfo 'WEACE Master Server installed successfully. You can install WEACE Master Adapters.'
        end

        return rError
      end

    end
  
  end
  
end
