
# This file has been generated by the installer of some Redmine's WEACE Slave Adapters.
# Do not modify it.
# It is used by some WEACE Slave Adapters scripts to get the environment necessary to access the underlying Redmine's database.

# The Ruby Gems library path
if [ -z ${RUBYLIB} ]
then
  export RUBYLIB=%{Repository}/rubygems/lib
else
  export RUBYLIB=${RUBYLIB}:%{Repository}/rubygems/lib
fi

# The Gems home
export GEM_HOME=%{Repository}/rubygems/gems

# The MySQL library path
if [ -z ${LD_LIBRARY_PATH} ]
then
  export LD_LIBRARY_PATH=%{Repository}/mysql/lib
else
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:%{Repository}/mysql/lib
fi
