# This configuration file has been generated by WEACESlaveClient on 2009-12-23 10:30:00
# You can edit it to reflect your configuration.
# Please check http://weacemethod.sourceforge.net for details about the contents of this file.

{
  # Registered WEACE Slave Adapters that are reachable from this WEACE Slave Client
  # Mandatory, list< map< Symbol, Object > >
  :WEACESlaveAdapters => [
     {
       :Product => 'DummyProduct',
       :Tool => 'DummyTool'
     },
     {
       :Product => 'DummyProduct',
       :Tool => 'DummyTool2'
     },
     {
       :Product => 'DummyProduct',
       :Tool => 'DummyTool4'
     },
     {
       :Product => 'DummyProduct2',
       :Tool => 'DummyTool3'
     },
     {
       :Product => 'DummyProduct2',
       :Tool => 'DummyTool4'
     }
  ]
}
