# Configuration file of RegRedmine.
# This file has been generated by WEACEInstall.rb on 2010-01-29 18:08:19.
# Parameters used for its generation: --redminedir E:/DOCUME~1/MURIEL~2/LOCALS~1/Temp/WEACERegression/Dir_0/redmine-0.8.2
# Feel free to modify it to accomodate to your configuration.


{
  :RedmineDir => '%{ProductDir}/redmine-0.8.2'
}
