# Configuration file of SlaveClient.
# This file has been generated by WEACEInstall.rb on 2010-01-29 16:29:24.
# Parameters used for its generation: --
# Feel free to modify it to accomodate to your configuration.


{
  # Log file used
  # String
  # :log_file => '/var/log/WEACESlaveClient.log',

  # List of WEACE Slave Adapters that can be used by WEACE Slave Client
  # map <
  #   <ProductName> => map <
  #     <ToolName> => list< <ActionName> >
  #   >
  # >
  :WEACESlaveAdapters => {
    'RegProduct' => {
      'DummyTool' => [
        'DummyAction',
        'DummyActionError',
        'DummyActionWithParams'
      ],
      'DummyTool2' => [
        'DummyAction2',
      ],
      'DummyTool4' => [
        'DummyAction4'
      ]
    },
    'RegProduct2' => {
      'DummyTool3' => [
        'DummyAction3'
      ],
      'DummyTool4' => [
        'DummyAction4'
      ]
    }
  }
}
