# File generated by WEACEInstall on 2010-01-29 18:08:19.
# !!! DO NOT MODIFY IT as it is used to keep track of what has been installed using WEACE Toolkit.
{
  :Type => 'Slave',
  :InstallationDate => '2010-01-29 18:08:19',
  :InstallationParameters => '--redminedir E:/DOCUME~1/MURIEL~2/LOCALS~1/Temp/WEACERegression/Dir_0/redmine-0.8.2',
  :Description => 'Product Redmine adapted to WEACE Slave.',
  :Product => 'Redmine',
  :Author => 'muriel@x-aeon.com'
}
