# File generated by WEACEInstall on 2010-01-29 18:08:19.
# !!! DO NOT MODIFY IT as it is used to keep track of what has been installed using WEACE Toolkit.
{
  :Type => 'Slave',
  :InstallationDate => '2010-01-29 18:08:19',
  :InstallationParameters => '--mediawikidir E:/DOCUME~1/MURIEL~2/LOCALS~1/Temp/WEACERegression/Dir_0/wiki',
  :Description => 'Mediawiki adapted to WEACE Slave.',
  :Product => 'Mediawiki',
  :Author => 'muriel@x-aeon.com'
}
