# Usage: This file is used by other files.
# Do not call it directly.
#
# Check http://weacemethod.sourceforge.net for details.
#--
# Copyright (c) 2009 Muriel Salvan (murielsalvan@users.sourceforge.net)
# Licensed under BSD LICENSE. No warranty is provided.
#++

module WEACEInstall

  module Slave
  
    class WEACESlaveClient
    
      include WEACEInstall::Common
      include WEACE::Common
      
      # Install for real.
      # This is called only when check method returned no error.
      #
      # Return:
      # * _Exception_: An error, or nil in case of success
      def execute
        rError = nil

        rError, lProviderEnv = getProviderEnv('Slave', @ProviderID, @AdditionalParameters)
        if (rError == nil)
          # Generate the WEACE environment file
          generateWEACEEnvFile
          if (lProviderEnv[:Shell] != nil)
            # Create the directory for Shell scripts
            require 'fileutils'
            FileUtils.mkdir_p(lProviderEnv[:Shell][:InternalDirectory])
            # Create the script that displays what is installed
            lShowComponentsFileName = "#{lProviderEnv[:Shell][:InternalDirectory]}/ShowWEACESlaveInfo.sh"
            File.open(lShowComponentsFileName, 'w') do |oFile|
              oFile << "\#!/usr/bin/env ruby
\# This file has been generated by the installation of WEACE Slave Client
begin
  \# Load WEACE environment
  require '#{@WEACEEnvFile}'
  require 'WEACEToolkit/Slave/DumpInfo'
  WEACE::Slave::DumpInfo.new.dumpTerminal
rescue Exception
  puts \"WEACE Slave Installation is corrupted: \#{$!}\"
end
"
            end
            FileUtils.chmod(0755, lShowComponentsFileName)
          end
          if (lProviderEnv[:CGI] != nil)
            # Generate the cgi script that will give details about the installed WEACE Slave Adapters
            lShowComponentsFileName = "#{lProviderEnv[:CGI][:InternalDirectory]}/WEACE/ShowWEACESlaveInfo.cgi"
            logDebug "Generate CGI script that shows installed WEACE Slave information (#{lShowComponentsFileName}) ..."
            require 'fileutils'
            FileUtils.mkdir_p(File.dirname(lShowComponentsFileName))
            File.open(lShowComponentsFileName, 'w') do |oFile|
              oFile << "\#!/usr/bin/env ruby
\# This file has been generated by the installation of WEACE Slave Client
\# Print header
puts 'Content-type: text/html'
puts ''
puts ''
begin
  \# Load WEACE environment
  require '#{@WEACEEnvFile}'
  require 'WEACEToolkit/Slave/DumpInfo'
  WEACE::Slave::DumpInfo.new.dumpHTML
rescue Exception
  puts \"WEACE Slave Installation is corrupted: \#{$!}\"
end
"
            end
            FileUtils.chmod(0755, lShowComponentsFileName)
          end
          logInfo 'WEACE Slave Client installed successfully. You can now install WEACE Slave Adapters and Listeners.'
        end

        return rError
      end
    
      # Get the default configuration
      #
      # Return:
      # * _String_: The default configuration text to put in the configuration file.
      def getDefaultConfig
        return "
{
  \# Log file used
  \# String
  \# :LogFile => '/var/log/WEACESlaveClient.log',

  \# List of WEACE Slave Adapters that can be used by WEACE Slave Client
  \# map <
  \#   <ProductName> => map <
  \#     <ToolName> => list< <ActionName> >
  \#   >
  \# >
  :WEACESlaveAdapters => {
  \# 'Redmine_01' => {
  \#   'TicketTracker' => [
  \#     'RejectDuplicate'
  \#   ]
  \# }
  }
}
"
      end

    end
  
  end
  
end
