# Usage: This file is used by other files.
# Do not call it directly.
#
# Check http://weacemethod.sourceforge.net for details.
#--
# Copyright (c) 2009 Muriel Salvan (murielsalvan@users.sourceforge.net)
# Licensed under BSD LICENSE. No warranty is provided.
#++

module WEACEInstall

  module Slave
  
    class WEACESlaveClient
    
      include WEACEInstall::Common
      include WEACE::Toolbox
      
      # Execute the installation
      #
      # Parameters:
      # * *iParameters* (<em>list<String></em>): Additional parameters to give the installer
      # Return:
      # * _Exception_: An error, or nil in case of success
      def execute(iParameters)
        rError = nil

        rError, lProviderConfig = getProviderConfig('Slave', @ProviderID, iParameters)
        if (rError == nil)
          # Store the way we retrieved the provider config in a file to be parsed for Adapters installations
          saveProviderConfig('Slave', @ProviderID, iParameters)
          if (lProviderConfig[:CGI] != nil)
            # Generate the cgi script that will give details about the installed WEACE Slave Adapters
            lShowComponentsFileName = "#{lProviderConfig[:CGI][:InternalDirectory]}/WEACE/ShowWEACESlaveInfo.cgi"
            logDebug "Generate CGI script that shows installed WEACE Slave information (#{lShowComponentsFileName}) ..."
            require 'fileutils'
            FileUtils.mkdir_p(File.dirname(lShowComponentsFileName))
            File.open(lShowComponentsFileName, 'w') do |iFile|
              iFile << "#!/usr/bin/env ruby
# This file has been generated by the installation of WEACE Slave Client
require 'WEACEToolkit/Slave/Client/ShowWEACESlaveInfo'
# Print header
puts 'Content-type: text/html'
puts ''
puts ''
WEACE::Slave::Dump_HTML.new.dumpWEACESlaveInfo_HTML
"
          end
          FileUtils.chmod(0755, lShowComponentsFileName)
          # Generate the environment file
          lEnvProviderFileName = "#{@WEACERepositoryDir}/Env_Slave.rb"
          logDebug "Generate environment file that will be used by WEACE Slave Adapters' installers (#{lEnvProviderFileName}) ..."
          File.open(lEnvProviderFileName, 'w') do |iFile|
            iFile << "# This file has been generated by Install_WEACESlaveServer.rb.
# It is used to give the environment of this provider to the WEACE Slave Adapters installers.
# This avoids developers to always give those parameters to any of the adapters installers.
# Its content depends on the WEACE Slave Client type (SourceForge, RubyForge...)
module WEACEInstall

  module Slave

    class ProviderEnv
    
      attr_reader :ProviderType
      attr_reader :CGIURL
    
      # Constructor
      def initialize
        @ProviderType = '#{@ProviderID}'
        @CGIURL = '#{lProviderConfig.CGIURL}'
      end
      
    end
    
  end
  
end
"
            end
          end
          logInfo 'WEACE Slave Client installed successfully. You can now install WEACE Slave Adapters and Listeners.'
        end

        return rError
      end
    
    end
  
  end
  
end
