#!/usr/bin/env ruby
# This file has been generated by the installer of the CGI listener from WEACE Toolkit.
# Do not modify it.
# It is used to route actions to WEACE Slave Client.
#
# More info on http://weacemethod.sourceforge.net

# Write header
puts 'Content-type: text/html'
puts ''
puts ''

# Redirect STDERR on STDOUT
$stderr.reopen $stdout

# Get the parameters
require 'cgi'
lCgi = CGI.new
lUserID = lCgi['userid']
lSerializedActions = lCgi['actions']

# Call WEACE Slave Client
require 'WEACEToolkit/Slave/Client/WEACESlaveClient'
if (WEACE::Slave::Client.new.executeMarshalled(lUserID, lSerializedActions))
  puts 'CGI_EXIT: OK'
else
  puts 'CGI_EXIT: ERROR'
end
