# This file is used by the WEACE Slave Adapters installers.
# Do not use it directly.
#
# Check http://weacemethod.sourceforge.net for details.
#--
# Copyright (c) 2009 Muriel Salvan (murielsalvan@users.sourceforge.net)
# Licensed under BSD LICENSE. No warranty is provided.
#++

module WEACEInstall

  module Slave
  
    module Adapters
    
      module Redmine
  
        module CommonInstall
          
          # Install the common part of every adapter for Redmine.
          #
          # Parameters:
          # * *iProviderEnv* (_ProviderEnv_): The provider environment
          def installRedmineWEACESlaveLink(iProviderEnv)
            # Modify the layouts/base view to add WEACE Master icon if not already present
            modifyFile("#{@RedmineDir}/app/views/layouts/base.rhtml",
              /Powered by <%= link_to Redmine/,
              "    <a title=\"Some content of this website can be modified by some WEACE processes. Click for explanations.\" href=\"#{iProviderEnv[:WEACESlaveInfoURL]}#Adapters.Redmine\"><img src=\"http://weacemethod.sourceforge.net/wiki/images/9/95/WEACESlave.png\" alt=\"Some content of this website can be modified by some WEACE processes. Click for explanations.\"/></a>\n",
              /<\/div>/)
          end

          # Generate the file that sets DB environment to using MySQL inside Ruby
          def generateDBEnv
            # Generate the database environment file that will be used by the Adapter scripts
            lDBEnvFileName = "#{@RedmineDir}/DBEnv.sh"
            logDebug "Generate database environment file for Redmine (#{lDBEnvFileName}) ..."
            File.open(lDBEnvFileName, 'w') do |iFile|
              iFile << "
# This file has been generated by the installer of some Redmine's WEACE Slave Adapters.
# Do not modify it.
# It is used by some WEACE Slave Adapters scripts to get the environment necessary to access the underlying Redmine's database.

# The Ruby Gems library path
if [ -z ${RUBYLIB} ]
then
  export RUBYLIB=#{@RubyGemsLibDir}
else
  export RUBYLIB=${RUBYLIB}:#{@RubyGemsLibDir}
fi

# The Gems home
export GEM_HOME=#{@GemsDir}

# The MySQL library path
if [ -z ${LD_LIBRARY_PATH} ]
then
  export LD_LIBRARY_PATH=#{@MySQLLibDir}
else
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:#{@MySQLLibDir}
fi
"
            end
          end
          
        end
        
      end
      
    end
    
  end
  
end
