# File generated by WEACEInstall on 2010-01-29 18:08:19.
# !!! DO NOT MODIFY IT as it is used to keep track of what has been installed using WEACE Toolkit.
{
  :Type => 'Master',
  :InstallationDate => '2010-01-29 18:08:19',
  :InstallationParameters => '--installdir E:/DOCUME~1/MURIEL~2/LOCALS~1/Temp/WEACERegression/Dir_0/WEACETools',
  :Description => 'WEACE Master processes that are accessible from a terminal.',
  :Product => 'CommandLine',
  :Author => 'murielsalvan@users.sourceforge.net'
}
