# File generated by WEACEInstall on 2010-01-29 16:29:24.
# !!! DO NOT MODIFY IT as it is used to keep track of what has been installed using WEACE Toolkit.
{
  :InstallationDate => '2010-01-29 16:29:24',
  :InstallationParameters => '--repository %{ProductDir}',
  :Description => 'The WEACE Slave Client.',
  :ProviderID => 'DummySlaveProviderWithCGI',
  :Author => 'muriel@x-aeon.com'
}
