# File generated by WEACEInstall on 2010-01-29 18:08:19.
# !!! DO NOT MODIFY IT as it is used to keep track of what has been installed using WEACE Toolkit.
{
  :InstallationDate => '2010-01-29 18:08:19',
  :InstallationParameters => '',
  :Description => 'Dummy Product used in WEACE Regression.',
  :Author => 'murielsalvan@users.sourceforge.net'
}
