# Usage: This file is used by other files.
# Do not call it directly.
#
# Check http://weacemethod.sourceforge.net for details.
#--
# Copyright (c) 2009 Muriel Salvan (murielsalvan@users.sourceforge.net)
# Licensed under BSD LICENSE. No warranty is provided.
#++

module WEACEInstall

  module Slave
  
    module Listeners
  
      class CGI
          
        # Install for real.
        # This is called only when check method returned no error.
        #
        # Return:
        # * _Exception_: An error, or nil in case of success
        def execute
          rError = nil

          # Get the CGI directory from the Provider environment
          if ((@ProviderEnv[:CGI] == nil) or
              (@ProviderEnv[:CGI][:InternalDirectory] == nil))
            rError = RuntimeError.new('Listener CGI can only be installed on Providers that are configured with CGI directories.')
          else
            lCGIDir = @ProviderEnv[:CGI][:InternalDirectory]
            # Generate the CGI script
            lCGIScriptFileName = "#{lCGIDir}/WEACE/Actions.cgi"
            logDebug "Generate CGI script (#{lCGIScriptFileName}) ..."
            require 'fileutils'
            FileUtils::mkdir_p(File.dirname(lCGIScriptFileName))
            File.open(lCGIScriptFileName, 'w') do |iFile|
              iFile << "#!/usr/bin/env ruby
# This file has been generated by the installer of the CGI listener from WEACE Toolkit.
# Do not modify it.
# It is used to route actions to WEACE Slave Client.
#
# More info on http://weacemethod.sourceforge.net

# Write header
puts 'Content-type: text/html'
puts ''
puts ''

# Redirect STDERR on STDOUT
$stderr.reopen $stdout

# Get the parameters
require 'cgi'
lCgi = CGI.new
lUserID = lCgi['userid']
lSerializedActions = lCgi['actions']

# Call WEACE Slave Client
require 'WEACEToolkit/Slave/Client/WEACESlaveClient'
if (WEACE::Slave::Client.new.executeMarshalled(lUserID, lSerializedActions))
  puts 'CGI_EXIT: OK'
else
  puts 'CGI_EXIT: ERROR'
end
"
              FileUtils.chmod(0755, lCGIScriptFileName)
            end
          end

          return rError
        end
        
      end
        
    end
    
  end

end
